_target_: src.model.fastsam.FastSAM
checkpoint_path: /mnt/personal/jelint19/weights/FastSAM/FastSAM-x.pt
segmentor_width_size: ${model.segmentor_width_size}
config:
  iou_threshold: 0.9
  conf_threshold: 0.05
  max_det: 200