# SAM2 Configuration
_target_: src.model.sam2.CustomSamAutomaticMaskGenerator
points_per_batch: 64
stability_score_thresh: 0.97
box_nms_thresh: 0.7
min_mask_region_area: 0
crop_overlap_ratio:
segmentor_width_size: ${model.segmentor_width_size}
sam:
  _target_: src.model.sam2.load_sam2
  model_type: sam2.1_hiera_large  # or sam2.1_hiera_tiny, sam2.1_hiera_small, sam2.1_hiera_base_plus
  checkpoint_dir: /mnt/personal/jelint19/weights/SegmentAnything2/
  # Optional: specify exact checkpoint and config files
  checkpoint_file: sam2.1_hiera_large.pt  # will be auto-resolved if not specified
  config_file: sam2.1/sam2.1_hiera_l.yaml  # will be auto-resolved if not specified