defaults:
  - user: default
  - machine: local
  - callback: base 
  - data: bop
  - model: cnos
  - _self_

save_dir: /mnt/personal/jelint19/results/cnos/${name_exp}
name_exp: cnos_exps
dataset_name: